version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvnw package -DskipTests
      finally:
        - mv mutant-2.1.7.RELEASE.jar ../
artifacts:
  files:
    - mutant-2.1.7.RELEASE.jar
  discard-paths: yes