name: test_coverage

on: [push]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
