name: build

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Check test coverage
        id: test-coverage
        uses: FredeHG/mutant@0.2
        with:
          percentage: "80"
          filename: "./target/site/jacoco/jacoco.xml"
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Coverage'
          status: ${{ steps.coverage.outputs.coverage }}
          path: ./badges/test-coverage.svg
          color: ${{ steps.coverage.outputs.coveragelines > 75 && 'green' || 'red' }}

