name: build

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: codecov
        uses: FredeHG/mutant@0.1
        with:
          files: ./target/site/jacoco-ut/jacoco.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
