name: build

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Upload coverage to Codecov
        uses: FredeHG/mutant@master
        with:
          files: ./jacoco.xml
          directory: ./target/site/jacoco-ut
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./target/site/jacoco-ut/codecov_report.txt
          verbose: true
